modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="cuntpants"
version="1.0.0"
displayName="CuntPants"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Manta, MCreator"

[[dependencies.cuntpants]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.cuntpants]]
    modId="just_enough_items"
    mandatory=false
    ordering="NONE"
    side="BOTH"

